==== Creating a new instance to the LenovoXclarity class

After a custom domain has been generated, the set of actions and events within the scope of that domain can be created.   The most straight forward way to create these definitions is to copy similar definitions from the default domain of the system and edit the definitions directly.

. Select the domain previously created and drill down Custom Domain name→ System → Event → EmsEvent →LenovoXclarity and select **(LenovoXclarity)**.

. Click **(Configuration)**, then click **(Add a new Instance)**.

. Enter the name

    .. The name must be equal to event name that will be managed, because Cloud Forms matches the instance with the event by the name.
    
    .. Find the name of the event that you wish in this link **<TO DO>**
    
    .. Copy the name of the event and past in the field’s name in Cloud Forms **(ex. FQXHMTS0003G)**.

. Add the path to the handlers copied in the field’s **rel3**.

    .. There are three policy operations:
        
        * Physical Server Reset
    
        * Physical Server Start

        * Physical Server Shutdown
    
    .. There are three policy events:

        * physical_server_reset

        * physical_server_start

        * physical_server_shutdown
        
    .. The policy operations and the policy events match.

    .. For example , when creating the **Physical Server Shutdown** policy provide the following path to the policy action:

        * /System/event_handlers/event_action_policy?target=physical_server&policy_event=**physical_server_shutdown**&param=
    
        * The policy_event value is matched with the policy operation applied.

. Click **Add**.